#############################################################################
# Makefile for building: Gallery
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Apr 5 01:09:42 2012
# Project:  Gallery.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile Gallery.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp \
		CPictureFlowWidget.cpp \
		CPicFlowWidget.cpp \
		CPicScrollWidget.cpp \
		CScrollWidget.cpp moc_dialog.cpp \
		moc_CScrollWidget.cpp \
		moc_CPictureFlowWidget.cpp \
		moc_CPicScrollWidget.cpp \
		moc_CPicFlowWidget.cpp \
		qrc_UiImgResources.cpp
OBJECTS       = main.o \
		dialog.o \
		CPictureFlowWidget.o \
		CPicFlowWidget.o \
		CPicScrollWidget.o \
		CScrollWidget.o \
		moc_dialog.o \
		moc_CScrollWidget.o \
		moc_CPictureFlowWidget.o \
		moc_CPicScrollWidget.o \
		moc_CPicFlowWidget.o \
		qrc_UiImgResources.o
DIST          = /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		Gallery.pro
QMAKE_TARGET  = Gallery
DESTDIR       = 
TARGET        = Gallery

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gallery.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile Gallery.pro
/usr/lib/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Gallery.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Gallery1.0.0 || $(MKDIR) .tmp/Gallery1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Gallery1.0.0/ && $(COPY_FILE) --parents dialog.h ui_CScrollWidget.hpp ui_CPicScrollWidget.hpp ui_CPicFlowWidget.hpp CScrollWidget.hpp CPictureFlowWidget.hpp CPicScrollWidget.hpp CPicFlowWidget.hpp ui_dialog.hpp .tmp/Gallery1.0.0/ && $(COPY_FILE) --parents UiImgResources.qrc .tmp/Gallery1.0.0/ && $(COPY_FILE) --parents main.cpp dialog.cpp CPictureFlowWidget.cpp CPicFlowWidget.cpp CPicScrollWidget.cpp CScrollWidget.cpp .tmp/Gallery1.0.0/ && $(COPY_FILE) --parents dialog.ui .tmp/Gallery1.0.0/ && (cd `dirname .tmp/Gallery1.0.0` && $(TAR) Gallery1.0.0.tar Gallery1.0.0 && $(COMPRESS) Gallery1.0.0.tar) && $(MOVE) `dirname .tmp/Gallery1.0.0`/Gallery1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Gallery1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dialog.cpp moc_CScrollWidget.cpp moc_CPictureFlowWidget.cpp moc_CPicScrollWidget.cpp moc_CPicFlowWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_CScrollWidget.cpp moc_CPictureFlowWidget.cpp moc_CPicScrollWidget.cpp moc_CPicFlowWidget.cpp
moc_dialog.cpp: dialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_CScrollWidget.cpp: ui_CScrollWidget.hpp \
		CScrollWidget.hpp
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) CScrollWidget.hpp -o moc_CScrollWidget.cpp

moc_CPictureFlowWidget.cpp: CPictureFlowWidget.hpp
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) CPictureFlowWidget.hpp -o moc_CPictureFlowWidget.cpp

moc_CPicScrollWidget.cpp: ui_CPicScrollWidget.hpp \
		CPicFlowWidget.hpp \
		ui_CPicFlowWidget.hpp \
		CPictureFlowWidget.hpp \
		CScrollWidget.hpp \
		ui_CScrollWidget.hpp \
		CPicScrollWidget.hpp
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) CPicScrollWidget.hpp -o moc_CPicScrollWidget.cpp

moc_CPicFlowWidget.cpp: ui_CPicFlowWidget.hpp \
		CPictureFlowWidget.hpp \
		CPicFlowWidget.hpp
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) CPicFlowWidget.hpp -o moc_CPicFlowWidget.cpp

compiler_rcc_make_all: qrc_UiImgResources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_UiImgResources.cpp
qrc_UiImgResources.cpp: UiImgResources.qrc \
		Images/scrollbar_h_leftArrow_pressed.png \
		Images/leftarrowdisabled.png \
		Images/greenBullet.png \
		Images/scrollbar_h_rightArrow_pressed.png \
		Images/scrollbar_h_body_pressed.png \
		Images/left4.png \
		Images/scrollbar_h_leftArrow.png \
		Images/scrollbar_h_bg.png \
		Images/scrollbar_h_rightArrow.png \
		Images/scrollbar_h_rightArrow_hover.png \
		Images/scrollbar_h_body_hover.png \
		Images/scrollbar_h_leftArrow_hover.png \
		Images/right4.png \
		Images/rightarrowdisabled.png \
		Images/blueBullet.png \
		Images/scrollbar_h_body.png
	/usr/lib/qt4/bin/rcc -name UiImgResources UiImgResources.qrc -o qrc_UiImgResources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h
ui_dialog.h: dialog.ui
	/usr/lib/qt4/bin/uic dialog.ui -o ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		ui_dialog.hpp \
		CPicScrollWidget.hpp \
		ui_CPicScrollWidget.hpp \
		CPicFlowWidget.hpp \
		ui_CPicFlowWidget.hpp \
		CPictureFlowWidget.hpp \
		CScrollWidget.hpp \
		ui_CScrollWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

CPictureFlowWidget.o: CPictureFlowWidget.cpp CPictureFlowWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPictureFlowWidget.o CPictureFlowWidget.cpp

CPicFlowWidget.o: CPicFlowWidget.cpp CPicFlowWidget.hpp \
		ui_CPicFlowWidget.hpp \
		CPictureFlowWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPicFlowWidget.o CPicFlowWidget.cpp

CPicScrollWidget.o: CPicScrollWidget.cpp CPicScrollWidget.hpp \
		ui_CPicScrollWidget.hpp \
		CPicFlowWidget.hpp \
		ui_CPicFlowWidget.hpp \
		CPictureFlowWidget.hpp \
		CScrollWidget.hpp \
		ui_CScrollWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPicScrollWidget.o CPicScrollWidget.cpp

CScrollWidget.o: CScrollWidget.cpp CScrollWidget.hpp \
		ui_CScrollWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CScrollWidget.o CScrollWidget.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_CScrollWidget.o: moc_CScrollWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CScrollWidget.o moc_CScrollWidget.cpp

moc_CPictureFlowWidget.o: moc_CPictureFlowWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CPictureFlowWidget.o moc_CPictureFlowWidget.cpp

moc_CPicScrollWidget.o: moc_CPicScrollWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CPicScrollWidget.o moc_CPicScrollWidget.cpp

moc_CPicFlowWidget.o: moc_CPicFlowWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CPicFlowWidget.o moc_CPicFlowWidget.cpp

qrc_UiImgResources.o: qrc_UiImgResources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_UiImgResources.o qrc_UiImgResources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

